### ISSUE TITLE
Latest sumneko-lua-ls release seems to have removed Linux/ and macOS/

### ISSUE THREAD

**Issue by oblitum** [xiyaowong/coc-sumneko-lua#10]
```
2021-12-17T12:42:52.401 ERROR (pid:82802) [extension:coc-sumneko-lua] - [Error: ENOENT: no such file or directory, chmod '/home/francisco/.config/coc/extensions/coc-sumneko-lua-data/sumneko-lua-ls/extension/server/bin/Linux/lua-language-server'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'chmod',
  path: '/home/francisco/.config/coc/extensions/coc-sumneko-lua-data/sumneko-lua-ls/extension/server/bin/Linux/lua-language-server'
}
```

**Comment by oblitum** [comment]
```
❯ ls ~/.config/coc/extensions/coc-sumneko-lua-data/sumneko-lua-ls/extension/server/bin/
```

**Comment by LLDay** [comment]
I have fixed the same issue with a symlink to an already installed lua language server

For Arch:
```
sudo pacman -S lua-language-server
mkdir -p ~/.config/coc/extensions/coc-sumneko-lua-data/sumneko-lua-ls/extension/server/bin/Linux/
ln -s /usr/bin/lua-language-server ~/.config/coc/extensions/coc-sumneko-lua-data/sumneko-lua-ls/extension/server/bin/Linux/lua-language-server
```

@xiyaowong, is there a reason to download the language server from https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery instead of https://api.github.com/repos/sumneko/lua-language-server/releases/latest?

Also, it would be nice to add the `serverPath` option for installed servers in coc-settings file

**Comment by xiyaowong** [comment]
@LLDay 
1. sumneko/lua-language-server publish asserts since 2.5.4
2. sometimes the latest version is not released in sumneko/vscode-lua
3. In my area, it is difficult to download files from GitHub without proxy

Anyway, I think API of vscode is the best choice:smile:
