### ISSUE TITLE
disable prompt: anonymous usage data

### ISSUE THREAD

**Issue by sabah1994** [xiyaowong/coc-sumneko-lua#43]
every time I open a lua file, I get this prompt, how do i turn it off?
![Screenshot from 2023-10-19 23-33-05](https://github.com/xiyaowong/coc-sumneko-lua/assets/73726199/f2233d5f-bb5e-4c74-b5f1-472986ed0d0c)

**Comment by sabah1994** [comment]
Note on vscode-lua:
[Privacy](https://github.com/LuaLS/vscode-lua#privacy)
The language server had opt-in telemetry that collected usage data and sent it to the development team to help improve the extension. Read our [privacy policy](https://luals.github.io/privacy#language-server) to learn more. Telemetry was removed in v3.6.5 and is no longer part of the language server.

Also I tried passing this arg:
    "telemetry": false,

**Comment by xiyaowong** [comment]
Option 2 doesn't work?

**Comment by sabah1994** [comment]
No It doesn't work, also I have 2 Ubuntu machines, it's happening on one of them and on both I have version 0.0.40 installed.

**Comment by xiyaowong** [comment]
Telemetry has been removed since v3.6.5. Run `:CocCommand sumneko-lua.checkUpdate` to upgrade your language server.

https://github.com/LuaLS/lua-language-server/wiki/Privacy#overview:~:text=Telemetry%20has%20been%20removed%20since%20v3.6.5%2C%20thank%20you%20for%20your%20positive%20feedback%20in%20the%20community!

**Comment by sabah1994** [comment]
Thank you.
